# Generated by Django 5.1.1 on 2024-10-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_badges'),
        ('accounts', '0003_remove_user_phone_regex_alter_user_phone_and_more'),
    ]

    operations = [
    ]
