# Generated by Django 5.1 on 2024-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_backgrounds/'),
        ),
    ]
