# Generated by Django 5.1.1 on 2024-10-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamesession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
