# Generated by Django 5.1.1 on 2024-10-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gameinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='level',
        ),
        migrations.RemoveField(
            model_name='level',
            name='prompt',
        ),
        migrations.AddField(
            model_name='level',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='level_images/')),
                ('order', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='game.level')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='game.story')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='game.scenario'),
        ),
    ]
