# Generated by Django 5.1.1 on 2024-10-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_action_level_remove_level_prompt_level_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='level_images/'),
        ),
    ]
