# Generated by Django 5.1.1 on 2024-12-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_outcome_action_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='points_explanation',
        ),
        migrations.AddField(
            model_name='outcome',
            name='action',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome', to='game.action'),
        ),
    ]
