# Generated by Django 5.1.1 on 2025-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_action_outcome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='intro_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
