# Generated by Django 5.1.1 on 2025-05-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_level_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_level',
            field=models.IntegerField(default=0),
        ),
    ]
