# Generated by Django 5.1.1 on 2025-05-29 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_animation'),
        ('game', '0011_gamesession_current_level'),
    ]

    operations = [
    ]
