# Generated by Django 5.1.1 on 2025-05-31 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_merge_0002_animation_0011_gamesession_current_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='current_level',
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('lives', models.IntegerField(default=3)),
                ('scenario_index', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('state_data', models.JSONField(blank=True, default=dict)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress',
                'unique_together': {('user', 'story')},
            },
        ),
    ]
