# Generated by Django 5.1.1 on 2025-06-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_gamesession_current_level_userprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('power_up_type', models.CharField(choices=[('extra_life', 'Extra Life'), ('score_boost', 'Score Boost'), ('time_extension', 'Time Extension'), ('hint', 'Hint')], default='extra_life', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='powerup_images/')),
                ('required_correct_answers', models.IntegerField(default=5, help_text='Number of correct answers needed to earn this power-up')),
                ('bonus_lives', models.IntegerField(default=0, help_text='Number of extra lives this power-up grants')),
                ('score_multiplier', models.FloatField(default=1.0, help_text='Multiplier for score (e.g., 2.0 doubles the score)')),
                ('time_extension_seconds', models.IntegerField(default=0, help_text='Additional time in seconds this power-up grants')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_ups', to='game.story')),
            ],
            options={
                'verbose_name': 'Power-up',
                'verbose_name_plural': 'Power-ups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserPowerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the power-up is currently active (false if used)')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('earned_level', models.IntegerField(default=0)),
                ('earned_scenario', models.IntegerField(default=0)),
                ('correct_answer_count', models.IntegerField(default=0, help_text='How many correct answers the user had when earning this')),
                ('game_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='power_ups', to='game.gamesession')),
                ('power_up', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_power_ups', to='game.powerup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Power-up',
                'verbose_name_plural': 'User Power-ups',
                'ordering': ['-earned_at'],
            },
        ),
    ]
